// Copyright © 2026 张鸿源. All Rights Reserved.
#include "Import/Assets/OmniImportRigAssets.h"
#include "Import/OmniCharacterImportProfile.h"
#include "AssetToolsModule.h"
#include "Engine/SkeletalMesh.h"
#include "Misc/PackageName.h"
#include "RetargetEditor/IKRetargetFactory.h"
#include "RetargetEditor/IKRetargeterController.h"
#include "Retargeter/IKRetargeter.h"
#include "Retargeter/IKRetargetChainMapping.h"
#include "Retargeter/IKRetargetSettings.h"
#include "Rig/IKRigDefinition.h"
#include "RigEditor/IKRigController.h"
#include "RigEditor/IKRigDefinitionFactory.h"

void Omni::CharacterImport::CreateRigAssets(USkeletalMesh* Mesh, const UOmniCharacterImportProfile& Profile,
	const FString& CharacterRoot, const FString& ResolvedName, const FImportReporter& Report)
{
	if (!Profile.bCreateIKRig) return;
	const FReferenceSkeleton& Skeleton = Mesh->GetRefSkeleton();
	if (Skeleton.FindBoneIndex(Profile.RetargetRoot) == INDEX_NONE)
	{
		Report(TEXT("IK Rig skipped: retarget root missing: ") + Profile.RetargetRoot.ToString(), true);
		return;
	}
	for (const FOmniImportRetargetChain& Chain : Profile.RetargetChains)
	{
		const int32 Start = Skeleton.FindBoneIndex(Chain.StartBone);
		const int32 End = Skeleton.FindBoneIndex(Chain.EndBone);
		int32 Ancestor = End;
		while (Ancestor != INDEX_NONE && Ancestor != Start) Ancestor = Skeleton.GetParentIndex(Ancestor);
		if (Chain.ChainName.IsNone() || Start == INDEX_NONE || End == INDEX_NONE || Ancestor != Start)
		{
			Report(TEXT("IK Rig skipped: invalid retarget chain: ") + Chain.ChainName.ToString(), true);
			return;
		}
	}
	const FString Folder = CharacterRoot / Profile.RigFolder;
	const FString RigName = TEXT("IK_") + ResolvedName;
	const FString RigPath = Folder / RigName + TEXT(".") + RigName;
	UIKRigDefinition* TargetRig = LoadObject<UIKRigDefinition>(nullptr, *RigPath, nullptr, LOAD_NoWarn);
	IAssetTools& AssetTools = FModuleManager::LoadModuleChecked<FAssetToolsModule>(TEXT("AssetTools")).Get();
	if (!TargetRig)
	{
		if (FPackageName::DoesPackageExist(Folder / RigName))
		{
			Report(TEXT("IK destination occupied by another asset: ") + RigPath, true);
			return;
		}
		TargetRig = Cast<UIKRigDefinition>(AssetTools.CreateAsset(RigName, Folder, UIKRigDefinition::StaticClass(), NewObject<UIKRigDefinitionFactory>()));
		if (!TargetRig)
		{
			Report(TEXT("Could not create IK Rig."), true);
			return;
		}
		UIKRigController* Controller = UIKRigController::GetController(TargetRig);
		if (!Controller->SetSkeletalMesh(Mesh))
		{
			Report(TEXT("IK Rig rejected the skeletal mesh."), true);
			return;
		}
		if (Profile.RetargetChains.IsEmpty())
		{
			if (!Controller->ApplyAutoGeneratedRetargetDefinition()) Report(TEXT("Auto retarget chain detection failed. Configure explicit chains in the profile."), true);
		}
		else
		{
			for (const FOmniImportRetargetChain& Chain : Profile.RetargetChains)
			{
				if (Controller->AddRetargetChain(Chain.ChainName, Chain.StartBone, Chain.EndBone, NAME_None).IsNone())
				{
					Report(TEXT("Could not create retarget chain: ") + Chain.ChainName.ToString(), true);
					return;
				}
			}
		}
		Controller->SetRetargetRoot(Profile.RetargetRoot);
		if (Profile.bTryAutoFBIK && !Controller->ApplyAutoFBIK()) Report(TEXT("Auto FBIK detection failed; review solver setup."), true);
		(void)TargetRig->MarkPackageDirty(); // Companion remains available for explicit saving.
		Report(TEXT("Created IK Rig: ") + TargetRig->GetPathName());
	}
	else if (UIKRigController::GetController(TargetRig)->GetSkeletalMesh() != Mesh)
	{
		Report(TEXT("Existing IK Rig belongs to another mesh; left unchanged: ") + RigPath, true);
		return;
	}
	UIKRigDefinition* SourceRig = Profile.SourceIKRig.LoadSynchronous();
	if (!SourceRig)
	{
		Report(TEXT("Retargeter pending: assign Source IK Rig in the profile."));
		return;
	}
	FString SourceLabel = Profile.SourceRigLabel;
	if (SourceLabel.IsEmpty())
	{
		SourceLabel = SourceRig->GetName();
		SourceLabel.RemoveFromStart(TEXT("IK_"));
	}
	const FString RetargetName = TEXT("IKR_") + SourceLabel + TEXT("To") + ResolvedName;
	if (FPackageName::DoesPackageExist(Folder / RetargetName))
	{
		Report(TEXT("Existing retargeter preserved: ") + RetargetName);
		return;
	}
	UIKRetargeter* Retargeter = Cast<UIKRetargeter>(AssetTools.CreateAsset(RetargetName, Folder, UIKRetargeter::StaticClass(), NewObject<UIKRetargetFactory>()));
	if (!Retargeter)
	{
		Report(TEXT("Could not create IK Retargeter."), true);
		return;
	}
	UIKRetargeterController* Controller = UIKRetargeterController::GetController(Retargeter);
	Controller->SetIKRig(ERetargetSourceOrTarget::Source, SourceRig);
	Controller->SetIKRig(ERetargetSourceOrTarget::Target, TargetRig);
	Controller->AddDefaultOps();
	Controller->AutoMapChains(EAutoMapChainType::Exact, false);
	(void)Retargeter->MarkPackageDirty();
	Report(TEXT("Created retargeter; retarget pose and animation require review: ") + Retargeter->GetPathName());
}
